apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/3 * * * *" # Run every 3 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cc-bepa
              image: erfan272758/cc-bepa:0.0.3
              envFrom:
                - configMapRef:
                    name: my-configmap
              env:
                - name: MONGO_USER
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: mongo_username
                - name: MONGO_PASS
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: mongo_password
                - name: EMAIL_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: email_token
              command: ["docker-entrypoint.sh"]
              args: ["node","/app/index.js"]
          restartPolicy: OnFailure
